### ISSUE TITLE
Xslate template engine benchmark info

### ISSUE THREAD

**Issue by topstarnetwork** [xslate/xslate.github.com#3]
Hello,
I am looking for a very fast lightweight cpu template engine,
could you tell me if you have any comparison benchmark as far as the other template engine here below are concerned with xlate performance?

1) Javascript template engine do T/

After some research it seems that doT template engine
https://github.com/olado/doT is the fastest + concise javascript template engine for nodejs and browsers. Partials, custom delimiters and more, after having checked this linkedin test report;

http://engineering.linkedin.com/frontend/client-side-templating-throwdown-mustache-handlebars-dustjs-and-more

2) Xslate template engine in perl

3) C C++ tempalte engines:

But I was told that c or c++ template engines are the fastest such as those once;

http://alexeyrybak.com/blitz/blitz_en.html or http://en.wikipedia.org/wiki/CTPP for php websites,
http://www.clearsilver.net/
http://teng.sourceforge.net/

My question is, as far as fastness and cpu load resource is concerned, do you think that a c, c++ template engine would make it better then the linkeding Dot template engin????

Regards, Heather

Template tool http://garann.github.io/template-chooser/

**Comment by lestrrat** [comment]
1. This is the repo for the xslate site. The xslate main repo is https://github.com/xslate/p5-Text-Xslate, if you have Xslate specific questions.
2. This is not a forum. It's an issue tracker (Although I don't blame you if you couldn't find one and decide to post here -- since xslate maintainers haven't really set up a proper forum). For general discussions you want to look elsewhere.
3. And finally, in your post you're basically comparing apples to oranges. There's no point in comparing rendering speed between different languages/environment without use context. For any of us, including you, to make any judgement, you need to have an actual use-case.
